POST http://localhost:3001/api/notes/
Content-Type: application/json

{
    "content": "new important note",
    "important": true,
    "userId": "689bb00d0bab78ea293bb801"
}

###
POST http://localhost:3001/api/notes/
Content-Type: application/json

{
    "content": "new note"
}
